### ISSUE TITLE
Loading a list of facebook profiles 

### ISSUE THREAD

**Issue by Tudorvr** [ThoughtfulDev/EagleEye#10]
Is it possible to offer a choice to users so they can load a list of facebook profiles urls to be compared to the face recognition phase, instead of browsing and collect with the webdriver the urls queried by name and surname? In a .txt file for e.g. or csv.

**Comment by ThoughtfulDev** [comment]
Totally possible! Great Idea by the way.
Will implements this soon.

**Comment by Tudorvr** [comment]
Tested & working! Thank you
