### ISSUE TITLE
No prediction given sry...No predictions found

### ISSUE THREAD

**Issue by waraga2** [ThoughtfulDev/EagleEye#100]
==> Enter the persons name to find on FB: Ariana Grande
==> How many jitters, higher is better [max 100] (default=70): 100
==> Opening Webdriver
-> Collecting Image URLs...(Page 1)

:: Starting Face Recognition
==> Loading known faces
-> Loading FB_IMG_15890732204883712.jpg

:: Analyzing
==> Storing Image in /tmp/XMYYST.jpg
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/p74x74/101153091_257799495425064_...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c6.6.74.74a/p86x86/292027_1418897...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c6.6.74.74a/p86x86/321094_1043832...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c13.13.168.168a/s74x74/321551_104...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c20.6.74.74a/p86x86/294360_101469...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/p74x74/27750724_111653612989345_6...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/p74x74/52412118_105830557220719_2...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c6.6.74.74a/p86x86/250043_1099951...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c6.6.74.74a/p86x86/250043_1099951...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c0.0.74.74a/p74x74/100667118_2901...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c7.0.74.74a/p74x74/71181313_10592...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c0.2.74.74a/p74x74/96718482_11531...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/p74x74/77088853_153715959341581_6...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/p74x74/91552643_2112529805559718_...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/c0.0.74.74a/p74x74/93776710_10046...
==> Analyzing https://z-p3-scontent.fmba2-1.fna.fbcdn.net/v/t1.0-1/cp0/p74x74/89861363_3140270612673825_...
==> Removing /tmp/XMYYST.jpg

:: Result
==> Found the following Profiles:

:: Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
-> Inserting Path
-> No Prediction given sry...
-> Collecting Links...(Page 1)
0
[]
-> Switching to Page 2
-> No more pages...

:: Validating Instagram Profiles

:: Links
[]

:: Predictions
[]
==> ERROR: No predictions found

:: Creating PDF Report
==> KTHXBYE

The screenshot of the pdf report is empty as shown below:
![eagle-eye](https://user-images.githubusercontent.com/67323245/85405341-f4697680-b568-11ea-8450-addcea4e590f.png)

Kindly help solve this issue, need to find Ariana Grande and confess the truth ;)
Long live EagleEye.

**Comment by waraga2** [comment]
Thanks ThoughtfulDev, you are the bomb💣

**Comment by azamet90** [comment]
> Thanks ThoughtfulDev, you are the bombbomb

yeah i did tested it recently and was not able to find the profile from tom cruise :D did u solve your problem? if yes how? i only get ERROR: No predictions found :)
