### ISSUE TITLE
I have trouble running EagleEye

### ISSUE THREAD

**Issue by MiChaelinzo** [ThoughtfulDev/EagleEye#104]
Traceback (most recent call last):
  File "eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 99, in main
    f.grabData()
  File "/home/user/EagleEye/grabber/facebook.py", line 16, in grabData
    driver = cfg.getWebDriver()
  File "/home/user/EagleEye/utils/config.py", line 45, in getWebDriver
    return webdriver.Firefox(profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
<img width="333" alt="eagleeye1" src="https://user-images.githubusercontent.com/68110223/92147024-39d8d880-ee23-11ea-89c8-ce1d7b5f7929.PNG">
<img width="478" alt="eagleeye2" src="https://user-images.githubusercontent.com/68110223/92147032-3d6c5f80-ee23-11ea-851e-b854b8e4db3a.PNG">

**Comment by ThoughtfulDev** [comment]
Did you follow the instructions? 
If Firefox is installed, download the latest release of the Geckodriver for you Architecture.

![image](https://user-images.githubusercontent.com/23433433/92255645-eaea7c00-eed2-11ea-8bf3-ff6843cba2e9.png)

**Comment by MiChaelinzo** [comment]
I did made geckodriver executable to everyone and set $PATH

**Comment by ThoughtfulDev** [comment]
Using the latest firefox and geckodriver?

**Comment by ThoughtfulDev** [comment]
I tried it with Firefox 80.0.1 and Webdriver 0.27.0 and had now issues.

**Comment by MiChaelinzo** [comment]
> I tried it with Firefox 80.0.1 and Webdriver 0.27.0 and had now issues.

i installed and run it manually without docker etc.

**Comment by ThoughtfulDev** [comment]
Try using my specified firefox and geckodriver version.

**Comment by MiChaelinzo** [comment]
> Try using my specified firefox and geckodriver version.

 firefox version 78.3.0esr (64-bit) and geckodriver 0.27.0 and selenium Version: 3.141.0

**Comment by ThoughtfulDev** [comment]
Try using the latest firefox with the latest geckodriver. (dont install geckodriver via npm but rather download it).

**Comment by MiChaelinzo** [comment]
> Try using the latest firefox with the latest geckodriver. (dont install geckodriver via npm but rather download it).

I can't run it with esr instead?

**Comment by ThoughtfulDev** [comment]
I am honestly not sure what causes the error. Seems like a mismatch in ff and geckodriver version. Thats why you can try using the latest version once.
