### ISSUE TITLE
error with entry.sh

### ISSUE THREAD

**Issue by lescuer97** [ThoughtfulDev/EagleEye#106]
Hi, i hope someone can help me, i'm trying to run the docker with the command given and modified the command as told to and i'm getting:  **/entry.sh: /entry.sh: is a directory**.

this is the command i used: sudo docker run -t --net=host --env="DISPLAY" \
                           --volume="$HOME/.Xauthority:/root/.Xauthority:rw"  \
                           -v  /home/leo/Downloads/software/EagleEye/known \
                           -v  /home/leo/Downloads/software/EagleEye/result \
                           -v /home/leo/Downloads/software/EagleEye/Repository/entry.sh:/entry.sh \
                           eagle-eye

thanks in advance for the help!

**Comment by ThoughtfulDev** [comment]
Check your path. Also try using bare-metal.

**Comment by DrunkenMoose** [comment]
> Check your path. Also try using bare-metal.

Hey man, I'm stuck at the same issue. I tried everything, also gave 777 permission etc.
Do you perhaps have a clue? The current working dir is just the EagleEye folder. And
the entry.sh file was there when I downloaded the project, so should be good to go right?
Thanks!

**Comment by ThoughtfulDev** [comment]
Try using the full path for the entry file and not a relative path. This seems to be a common docker issue (not really related to this project)

**Comment by DrunkenMoose** [comment]
> Try using the full path for the entry file and not a relative path. This seems to be a common docker issue (not really related to this project)

Hey man, yea I tried that too of course, in many forms. so "/home/etc/etc/EagleEye/entry.sh" or ./ or ~/ all of it.
Is it maybe because there is an error generated, but that is shown as "entry.sh is a directory?"

Because when I run "sudo python3 eagle-eye.py -h" then it shows a whole different error "No module named 'requests_html'" which means it maybe go further than the first rule?

**Comment by DrunkenMoose** [comment]
I found out that when you change /entry.sh on the bottom of the dockerfile and change it with ./entry.sh it will go on.
It looks like the error is coming from the bash command out of docker. So indeed nothing to do with eagle-eye.
Now I get other errors, but I will try to continue on.
