### ISSUE TITLE
Issue using with Docker image and opencv.

### ISSUE THREAD

**Issue by kampfire** [ThoughtfulDev/EagleEye#111]
Hello, I'm on macOS Catalina, have Python installed with pyenv (3.9.0).

```
docker run -t --net=host --env="DISPLAY" \
                           --volume="$HOME/.Xauthority:/root/.Xauthority:rw"  \
                           -v  ~/projects/EagleEye/search/known:/EagleEye/known \
                           -v  ~/projects/EagleEye/search/result:/result \
                           -v ~/projects/EagleEye/entry.sh:/entry.sh \
                           eagle-eye
```

Installs without any issue using Docker image, but when I try to run the previous I keep getting this error:

```
Traceback (most recent call last):
  File "eagle-eye.py", line 13, in <module>
    from face_recog import FaceRecog
  File "/EagleEye/face_recog.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

I manually installed with `pip3 install opencv-python`, same with `face_recognition` and `requests-html`. I'm worried that I tried with `sudo` at one point out of desperation and that probably made things worse.. Which directory am I meant to run this from? Does it matter? Any idea what I could be doing wrong? Thank you.

**Comment by ThoughtfulDev** [comment]
Seems like this is a issue with opencv not finding opengl on your system. 

I would rather post this to opencv github/issue tracker.

**Comment by nutt318** [comment]
I'm having the same issue, anyone happen to find the fix for this?

**Comment by pcnoic** [comment]
Verify that `libgl1-mesa-glx` is installed in your system. Taken from: https://github.com/opencv/opencv/issues/18359#issuecomment-717717921
