### ISSUE TITLE
CAN-U-MAKE-THIS-FOR-WINDOWS

### ISSUE THREAD

**Issue by morpheuslord** [ThoughtfulDev/EagleEye#113]
hello 
i am morpheuslord
i am a hacking student and i am a hackers framework developer and for my new tool and i wanted to add ur tool to the framework 
its for windows users only so i wanted to ask if u can recreate this to for windows
and can u change it from firefox to chrome 
u can message me to my twitter @morpheuslord2

thank you
morpheuslord

**Comment by jameslm92** [comment]
Hello morpheuslord,

It's a pleasure to meet you and thank you for taking the time and respect
to write me and ask me the questions you have.  You are welcome to use the
code but as for the same respect you have shown me I must show the original
author.  I did not write the code myself.  I meant to host it to use to
fall back on as a matter copy.  I didn't realize it was listed public.  So
as I do appreciate your time you took I however feel I would be stealing
the credit from the original producer/s.  I will look into my changes and
see if I have or did make the variant that you are seeking for Windows
Chrome.

Best regards

Jim

**Comment by ThoughtfulDev** [comment]
Hey @morpheuslord : there are no plans to make it run on windows currently. You are welcome to open a pull request.

@jameslm92  do you mind elaborating what you are talking about? ;)

**Comment by morpheuslord** [comment]
Well can u give the link to the chrome varrient I will try to see if I can modify it to run on window's
