### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JunPham** [ThoughtfulDev/EagleEye#118]
I using Python 3.8.5.
OS: Ubuntu 20.04.2 LTS
known: ronaldo.jpg
Docker version 20.10.7, build f0df350
And i got this error, help me please
![ronaldo](https://user-images.githubusercontent.com/42670522/122797960-3d721900-d2ea-11eb-806a-7f02b968c052.jpg)
![error](https://user-images.githubusercontent.com/42670522/122797727-fc7a0480-d2e9-11eb-9541-7025b9453315.png)

**Comment by ThoughtfulDev** [comment]
Refer to #117
