### ISSUE TITLE
Error running in ubuntu shell in windows 10!

### ISSUE THREAD

**Issue by Tudorvr** [ThoughtfulDev/EagleEye#12]
Any idea why this error?
==> How many jitters, higher is better [max 100]: 20
==> Opening Webdriver
  -> Collecting Image URLs...(Page 1)
  -> Collecting Images URLs...(Page 2)
  -> Collecting Images URLs...(Page 4)
  -> Collecting Images URLs...(Page 3)
  -> Collecting Images URLs...(Page 5)

:: Starting Face Recognition
==> Loading known faces
==> ERROR: No Face Encodings found!
==> ERROR: Did you call `loadKnown(label)` before calling this method?
Traceback (most recent call last):
  File "eagle-eye.py", line 224, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=args.skipyandex, FBUrls=[])
  File "eagle-eye.py", line 88, in main
    profile_links, profile_imgs = r.getValidLinksAndImg(name)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by ThoughtfulDev** [comment]
This either means that you dont have any Faces in your `known` folder or that no faces were found in any of the images in the `known` folder.
