### ISSUE TITLE
The command '/bin/sh -c apt-get update && add-apt-repository -y ppa:deadsnakes/ppa && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3.6 python3.6-dev' returned a non-zero code: 100

### ISSUE THREAD

**Issue by Wick-McLean** [ThoughtfulDev/EagleEye#140]
Hello, I am getting the following error using Ubuntu 18.04.06 LTS. It appears that the dockerfile is unable to download the python 3.6 repository, although I don't know if this is actually the case, or why that would be. 

My apologies if this is simple or obvious, I have spent a number of hours trying to figure this out online and I have tried to alter the dockerfile with no success. 

Thank you

----

Step 11/24 : RUN apt-get update && add-apt-repository -y ppa:deadsnakes/ppa && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3.6 python3.6-dev
 ---> Running in 1989c7d1d5t4
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [99.8 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [99.8 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [97.4 kB]
Fetched 297 kB in 0s (471 kB/s)
Reading package lists...
gpg: keyring `/tmp/tmpve2yk1bu/secring.gpg' created
gpg: keyring `/tmp/tmpve2yk1bu/pubring.gpg' created
gpg: requesting key 6A758676 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpve2yk1bu/trustdb.gpg: trustdb created
gpg: key 6A758676: public key "Launchpad PPA for deadsnakes" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial InRelease [18.1 kB]
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Fetched 18.1 kB in 0s (33.7 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python3.6
E: Couldn't find any package by glob 'python3.6'
E: Couldn't find any package by regex 'python3.6'
E: Unable to locate package python3.6-dev
E: Couldn't find any package by glob 'python3.6-dev'
E: Couldn't find any package by regex 'python3.6-dev'
The command '/bin/sh -c apt-get update && add-apt-repository -y ppa:deadsnakes/ppa && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3.6 python3.6-dev' returned a non-zero code: 100

**Comment by Lyzoic-bit** [comment]
I'm getting same error, can anyone adjust? What I googled is that ppa repository have been replaced with new but how can I add it other way, when making the docker file, it automatically tries get the older ppa

**Comment by ThoughtfulDev** [comment]
Current dockerfile is using ubuntu 16.04. try that. for later version you dont need a ppa. py3.9 works fine.
