### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by kisuke87** [ThoughtfulDev/EagleEye#142]
please a method to fix this

![kisuke  Running  - Oracle VM VirtualBox 3_5_2022 11_35_53 PM](https://user-images.githubusercontent.com/101023710/156901993-9018581f-aebf-4e6c-8c8f-b201853a3ca2.png)

**Comment by ThoughtfulDev** [comment]
Has nothing to do with this. program. You seem to use another program...check https://github.com/karma9874/AndroRAT
