### ISSUE TITLE
Getting a weird error when i run the code

### ISSUE THREAD

**Issue by josephmiller2000** [ThoughtfulDev/EagleEye#18]
Attaching screenshot, so you can check it out.

i'm using ubuntu 16

![snap_2018 07 03_21h37m26s_003_](https://user-images.githubusercontent.com/24210340/42231913-83566a7a-7f0a-11e8-86b5-a73607c532e1.png)

**Comment by ThoughtfulDev** [comment]
I'm using [requests-html](https://github.com/kennethreitz/requests-html) for parsing instagram. This package only supports python 3.6. Try Python 3.6

**Comment by josephmiller2000** [comment]
Here you go,
![snap_2018 07 03_21h54m05s_004_](https://user-images.githubusercontent.com/24210340/42232316-a7b7a6b2-7f0b-11e8-8367-1598f426bdf4.png)

**Comment by ThoughtfulDev** [comment]
You sure that your `python3` command is symlinked to python 3.6?
try: `python3 -V`

i just tried it (even with python 3.5) and it worked using a fresh virtualenv.
Try using a fresh virtualenv e.g
`pip3 install virtualenv`
then
```
virtualenv -p python3 venv
source venv/bin/activate
which python #should point to the venv directory
pip install -r requirements.txt
pip install --upgrade beautifulsoup4 html5lib spry
python eagle-eye -h
```
Thats what i did. 

I also looked for the Issue in the requests-html repo but couldnt find anything...indeed weird.

**Comment by josephmiller2000** [comment]
I tried the manual mode and end up getting this error.
Yes it is 3.6
![snap_2018 07 03_22h33m30s_006_](https://user-images.githubusercontent.com/24210340/42234241-8e3c00f6-7f11-11e8-8c9f-5eef88c47a06.png)
![snap_2018 07 03_22h36m14s_007_](https://user-images.githubusercontent.com/24210340/42234245-8f36132a-7f11-11e8-8e73-840d05a8bbef.png)

**Comment by ThoughtfulDev** [comment]
Your pip has some SSL Errors so it cant fetch `urllib3`. I suggest that you try a fresh Ubuntu 16.04 VM.
You can try to install `urllib3` directly from Github with:
`sudo pip3 install https://github.com/urllib3/urllib3/archive/master.zip`

**Comment by josephmiller2000** [comment]
damnn my luck is bad i guess.. i even tried installing new Ubunto and end up getting error with PIP3 again.

In default, Ubuntu 16 used 6.5 python3,   I moved from 6.5 to 6.6.

Still end up with pip3 error. No idea how to fix this.

**Comment by ThoughtfulDev** [comment]
Try upgrading your pip with `pip3 install --upgrade pip`

Some people say that it has to do with some SSL infrastructure changes in pypi.
Also make sure that `python3-openssl` is installed :`sudo apt-get install python3-openssl `

**Comment by josephmiller2000** [comment]
oh god, i'm tired of this stupid PIP lol sorry.

i even moved to kali linux, which have all latest python, but the pip3 is keep making messes.

![snap_2018 07 04_13h28m31s_001_](https://user-images.githubusercontent.com/24210340/42264456-465a2fb0-7f8e-11e8-8892-cab736483ae3.png)

**Comment by josephmiller2000** [comment]
PIP install error
![snap_2018 07 04_13h46m26s_002_](https://user-images.githubusercontent.com/24210340/42265277-b1f981e2-7f90-11e8-99c8-4be0da9bffd2.png)

**Comment by ThoughtfulDev** [comment]
`python3`, `python3-pip` and `python3-dev` are found using the latest Kali Liveboot (just tried it). 
Something is really wrong.
I might upload a VirtualBox Image that one can use.

**Comment by josephmiller2000** [comment]
Holly Crap After several tries, now it works in UBUNTU 18

![snap_2018 07 04_16h57m51s_003_](https://user-images.githubusercontent.com/24210340/42274797-9fb5bee0-7fab-11e8-8051-aa061d468717.png)

**Comment by ThoughtfulDev** [comment]
Great!
Mind telling me what you did differently or what you changed? :+1:

**Comment by josephmiller2000** [comment]
Nothing different, just moved to ubuntu 18 version ( fresh install ) 

then tried your automatic wget code, and it works like a charm , after added web driver.

But now i end up getting an error BROKEN PIPE

![snap_2018 07 04_17h15m28s_005_](https://user-images.githubusercontent.com/24210340/42275479-11a2abce-7fae-11e8-8269-e6c63a04e92f.png)
