### ISSUE TITLE
pip3 error 

### ISSUE THREAD

**Issue by gearcapitan** [ThoughtfulDev/EagleEye#2]
![kali_linux_2018-2018-02-26-15-27-29](https://user-images.githubusercontent.com/13740942/36696363-990c5be6-1b09-11e8-8a12-ed54b1dbeeab.png)

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-unaqumcx/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-eoo_15cy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-unaqumcx/dlib/

**Comment by ThoughtfulDev** [comment]
Make sure that you have `cmake` installed e.g
```
sudo apt install cmake
```

Just tested it on a kali live boot and it worked that way.

**Comment by ThoughtfulDev** [comment]
Closing since no response.
