### ISSUE TITLE
Install script breaks on non-debian systems

### ISSUE THREAD

**Issue by imnotbad** [ThoughtfulDev/EagleEye#21]
The install script assumes a lot of things, one of them is that the `apt` tool is installed on the target system. It might be a good idea to either check that the OS is debian/debian-based, or to print a warning beforehand about this script only working on debian-based systems.

**Comment by ThoughtfulDev** [comment]
Yes will do.
Thanks!

**Comment by ThoughtfulDev** [comment]
Added Debian-based an Arch compatibility.
Still working on Fedora since i dont know the package names for yum (and i dont have a VM right now).
