### ISSUE TITLE
no module named utils.console

### ISSUE THREAD

**Issue by psychomad** [ThoughtfulDev/EagleEye#24]
Hi
Just want share an issue happened to me and i have no clue how fix it

Followed all instrutions and still same problem

no mdoule named: requests-html
no module named face_recognition

Any help?

**Comment by ThoughtfulDev** [comment]
Try installing those manually

```
sudo pip3 install requests-html
sudo pip3 install face_recognition
```

Both must have thrown an error when installing via the script (which the script ignores since it just runs commands).

If the above commands worked without any errors , then this should give some output:
```
$ pip3 freeze | grep requests #should print requests-html==...
$ pip3 freeze | face  #should print face_recognition==...
```

**Comment by cr4shcod3** [comment]
@psychomad what's your python version and your OS?

**Comment by psychomad** [comment]
Hi

kali 2018 OS
Python 3.6.6 (default, Jun 27 2018)

I tried what you suggest and output is:

 pip3 install requests-html
Requirement already satisfied: requests-html in /usr/local/lib/python2.7/dist-packages (0.2.2)
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from requests-html) (0.0.1)
Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages (from requests-html) (1.8.4)
Requirement already satisfied: fake-useragent in /usr/local/lib/python2.7/dist-packages (from requests-html) (0.1.10)
Requirement already satisfied: pyquery in /usr/local/lib/python2.7/dist-packages (from requests-html) (1.4.0)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from requests-html) (2.7.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4->requests-html) (4.6.0)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python2.7/dist-packages (from pyquery->requests-html) (4.1.0)
Requirement already satisfied: cssselect>0.7.9 in /usr/lib/python2.7/dist-packages (from pyquery->requests-html) (1.0.3)
 I think the problem is... python point to v2 and not 3.... im right?

**Comment by ThoughtfulDev** [comment]
I tried the live boot version of the newest Kali Iso.
`pip3 install requests-html`
installs into `/usr/local/lib/python3.6/...` which is correct.
check your Kali installation (and update it) or try the liveboot version.

**Comment by cr4shcod3** [comment]
For me, running the install.sh installs all required modules, packages, etc.

**Comment by psychomad** [comment]
Found the solution:
@ThoughtfulDev : yes on a new clean Kali no problem, but as i said i use a customized Kali and problem is about have python2 and python3 .

Solution:
Need to specify to use a virtualenv on python3

virtualenv -p python3 myvenv
then
source myvenv/bin/activate

in this way everything point to python3 only and then all goes fine.

**Comment by ThoughtfulDev** [comment]
Thanks for reporting back.
Glad you fixed it.
