### ISSUE TITLE
[Request] Alternative To Using A Name

### ISSUE THREAD

**Issue by zero77** [ThoughtfulDev/EagleEye#3]
Can you please ad an option to skip the name or use an email or username, for if you don’t know the name.
Thanks

**Comment by ThoughtfulDev** [comment]
I dont know if Facebook supports searching for a email/phonenumber without being logged in.
Or did i missunderstood your request?

**Comment by zero77** [comment]
I don’t think I explained this well, but I was meaning the skip option for Facebook and the rest for the google search or other search engines.

**Comment by ThoughtfulDev** [comment]
So you want to skip the  FB Section , which is fine.
And instead of searching for the found FB Photos on Google Image Search you want to search for a email or username in google image and compare those results against your known image?

**Comment by zero77** [comment]
Yes, skip FB if you don’t have useful info to use.

But, you could try different searches in google or other SE (search engines), like an email or a username or an image or other info you have, to build a profile and expand your searches from there.

I guess what I mean is to search with different info that you have across different SE and social networks to create a more extensive report.

**Comment by ThoughtfulDev** [comment]
I get what you mean. I have to expand my webscraping knowledge to do this kind of Stuff.
What you are describing seems similar to what Maltego does but i will keep that i mind (especially the skipping FB Option).

You can always contribute by doing a pull request ofcourse ;)
