### ISSUE TITLE
Crashes when running

### ISSUE THREAD

**Issue by asiudoisjdfo** [ThoughtfulDev/EagleEye#31]
==> Enter the persons name to find on FB: bob
==> How many jitters, higher is better [max 100]: 100
==> Opening Webdriver
  -> Collecting Image URLs...(Page 1)
  -> Collecting Images URLs...(Page 4)
  -> Collecting Images URLs...(Page 2)
  -> Collecting Images URLs...(Page 3)
  -> Collecting Images URLs...(Page 5)

:: Starting Face Recognition
==> Loading known faces
==> ERROR: No Face Encodings found!
==> ERROR: Did you call `loadKnown(label)` before calling this method?
Traceback (most recent call last):
  File "eagle-eye.py", line 229, in <module>
    main(skipFB=args.skipfb, skipIR=args.skipir, skipY=None, FBUrls=[])
  File "eagle-eye.py", line 87, in main
    profile_links, profile_imgs = r.getValidLinksAndImg(name)
ValueError: not enough values to unpack (expected 2, got 0)

Used install.sh on ubuntu 18.04

**Comment by ThoughtfulDev** [comment]
As the Error states no Faces where found in anyone of the Images in the `known` Folder.

I fixed the Crash in the latest commit but make sure to use other known images until the Error goes away(which means faces where found in one of the known images)

**Comment by asiudoisjdfo** [comment]
jesus christ im going blind - sorry about this!

**Comment by ThoughtfulDev** [comment]
You can open an Issue. Or ideally you could make a pull request if you want to implement your idea ;)
