### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by evilcoder13** [ThoughtfulDev/EagleEye#32]
![image](https://user-images.githubusercontent.com/19726972/43128549-756af162-8f5c-11e8-9064-b9d17ae3440c.png)
After installed automatically and added required python package using pip, got this error when running as per instructed.

**Comment by ThoughtfulDev** [comment]
Duplicate of #26 

Check Issue #18
Tl;dr: try Python 3.6
