### ISSUE TITLE
FileNotFoundError even all configured

### ISSUE THREAD

**Issue by ThigSchuch** [ThoughtfulDev/EagleEye#37]
![image](https://user-images.githubusercontent.com/20743110/43723015-0aa5f096-996d-11e8-8182-f16c6e56e29a.png)

![image](https://user-images.githubusercontent.com/20743110/43723034-16aece1c-996d-11e8-96c6-7e854546f36e.png)

![image](https://user-images.githubusercontent.com/20743110/43723141-4e04eebe-996d-11e8-8d25-5f4f1c306742.png)

**Comment by ThoughtfulDev** [comment]
Move the `geckodriver` to `/usr/bin` and change the path to `/usr/bin/geckodriver`.
Then try again.

**Comment by ThigSchuch** [comment]
Worked, thanks.

A detail, if copy path from properties, come with "user" not "usr".
