### ISSUE TITLE
Error :Firefox profile is missing 

### ISSUE THREAD

**Issue by beer-to-code** [ThoughtfulDev/EagleEye#40]
get an error message when i try to accesss

**Comment by ThoughtfulDev** [comment]
A screenshot perhaps?
Try opening firefox normally once before using the tool.

**Comment by mackhossain** [comment]
i got some problem.
![kali eagle eye problem](https://user-images.githubusercontent.com/38070162/50593529-e2060380-0ec2-11e9-966d-77a06b13114c.jpg)

**Comment by ThoughtfulDev** [comment]
Please open a new issue for this, so that i dont confuse this.
