### ISSUE TITLE
install webdriver 

### ISSUE THREAD

**Issue by ccrmj24** [ThoughtfulDev/EagleEye#43]
Hello every body i have a problem with this : /usr/local/bin/geckodriver does not exist - install a webdriver
what can i do .

**Comment by ThoughtfulDev** [comment]
Download the [latest release](https://github.com/mozilla/geckodriver/releases/latest) of the Geckodriver for you Architecture and put it into /usr/local/bin/geckodriver (in your case)

**Comment by ccrmj24** [comment]
NO my friend i have the same rpoblem . i pass to /usr/local/bin/geckodriver
but nothing .i download the version 0.17 because i check if i have firefox
esr i need to donwload  this version.

**Comment by ThoughtfulDev** [comment]
You do ofc need to change the path in `config.json`
