### ISSUE TITLE
Undefined symbol: cblas_dtrsm

### ISSUE THREAD

**Issue by Dentrax** [ThoughtfulDev/EagleEye#44]
I did the setup by watching all the steps one by one. I didn't get any error in setup progress.

When i run command: `python3 eagle-eye.py`

I get this output:

```
Traceback (most recent call last):
  File "eagle-eye.py", line 16, in <module>
    from face_recog import FaceRecog
  File "/home/dentrax/Projects/GitHub/EagleEye/face_recog.py", line 2, in <module>
    import face_recognition
  File "/usr/lib/python3.7/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/usr/lib/python3.7/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
ImportError: /usr/lib/python3.7/site-packages/dlib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cblas_dtrsm
```

`pip -V` : `pip 18.0 from /usr/lib/python3.7/site-packages/pip (python 3.7)`

`python --version` : `Python 3.7.1`

`uname -r` : `4.19.4-arch1-1-ARCH`

`cython --version` : `Cython version 0.29.1`

**Comment by ThoughtfulDev** [comment]
Seems to be an issue regarding `dlib`(openblas) not EagleEye.
Try following this: [https://github.com/davisking/dlib/issues/822](https://github.com/davisking/dlib/issues/822) and [https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts](https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts)
