### ISSUE TITLE
Reverse image/name search

### ISSUE THREAD

**Issue by tacticalDevC** [ThoughtfulDev/EagleEye#49]
Sometimes you just have a image or a name from your target. This would be an improvement if you simply don't know the name of your target or you heard a name but you don't have an image.

**Comment by ThoughtfulDev** [comment]
Use the --skipfb option. This skips the facebook search thus you dont need a name e.g
`python eagle-eye.py --skipfb`

**Comment by tacticalDevC** [comment]
But what if you have a name and no image? Therefore it would be nice if you wouldn't have to do --skipfb

**Comment by ThoughtfulDev** [comment]
Whats so bad about --skipfb? this way you dont need a name.
This is useless without at least one image. How do you know if the image is correct? We do face recognition using the image you supply vs the images it finds to match the correct ones.
