### ISSUE TITLE
No Face Encodings found

### ISSUE THREAD

**Issue by Cyper24** [ThoughtfulDev/EagleEye#50]
![1](https://user-images.githubusercontent.com/36534858/50766512-17886380-12ac-11e9-9a5a-f013aa009ec9.png)

i always got this ,why?

**Comment by ThoughtfulDev** [comment]
Make sure that you have placed at least one image in the `known` folder.
If you have already placed a image in this folder try to increase the jitter (input is at the beginning of the script)

**Comment by Cyper24** [comment]
![3](https://user-images.githubusercontent.com/36534858/50895452-b93cbb80-1438-11e9-8ba8-1848b00b34af.png)
but i got this for all image

**Comment by ThoughtfulDev** [comment]
Try using Linux e.g a Ubuntu vm since this has only been tested using Linux

**Comment by Cyper24** [comment]
![screenshot from 2019-01-11 22-05-37](https://user-images.githubusercontent.com/36534858/51042154-2c3b6300-15ee-11e9-8b65-f368f3e6d13f.png)

got same in ubuntu 18.04

**Comment by ThoughtfulDev** [comment]
Can you link the images or if they are private send via Twitter? (can be found on my website: thoughtful-dev.com)
