### ISSUE TITLE
requests_html error

### ISSUE THREAD

**Issue by JimChrModder** [ThoughtfulDev/EagleEye#51]
I did Automated Prequisites Installation
then I followed your instructions,but when I run the command "python3 eagle-eye.py" it says this error:

Traceback (most recent call last):
  File "/root/EagleEye/eagle-eye.py", line 14, in <module>
    from grabber.instagram import InstagramGrabber
  File "/root/EagleEye/grabber/instagram.py", line 1, in <module>
    from requests_html import HTMLSession
ModuleNotFoundError: No module named 'requests_html'

**Comment by JimChrModder** [comment]
Also I had this error at installation process:

    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************
    
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-r2_aa_xi/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-st98h40u/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-r2_aa_xi/dlib/

**Comment by ThoughtfulDev** [comment]
and as the error says. Cmake must be installed. So install cmake
