### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [ThoughtfulDev/EagleEye#52]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by ThoughtfulDev** [comment]
This depends on a handfull of python libs e.g tensorflow and dlib (c++).
This also uses external configuration files e.g `config.json` and the `known` folder.

Do you have a particular reason you need a appimage? You can easily install required packages via pip (python 3.6+) on linux which should just work. If you want isolation you can use a virtualenv so you dont install the packages globally.

**Comment by zero77** [comment]
There are a number of reasons i would like to see AppImage support added.

Because, it can help when you don't have root access to install Eagle Eye or dependencies.

Also, it's easier to use on a new install or on a different device than usual from a usb.

**Comment by ThoughtfulDev** [comment]
Do you want to help creating a AppImage? You are more than welcome to do so.

**Comment by zero77** [comment]
I will have a look into it.
I think the best solution is.
> Bundling your Travis CI builds as AppImages

But i haven't had a look yet.
