### ISSUE TITLE
Cannot import face_recognition on python3.6.8

### ISSUE THREAD

**Issue by G90DD** [ThoughtfulDev/EagleEye#54]
Using python3.6.8, cannot import face_recognition, getting the below error:

Command "/home/george/EagleEye/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vfg0i0dv/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-pwnyeh3e/install-record.txt --single-version-externally-managed --compile --install-headers /home/george/EagleEye/venv/include/site/python3.6/dlib" failed with error code 1 in /tmp/pip-install-vfg0i0dv/dlib/

All the other requirements are installed without problems.

Any ideas?

**Comment by ThoughtfulDev** [comment]
Which os are you using?
Please try using a Ubuntu 16.04 VM.
Try uninstalling face_recognition and dlib.
Then install only dlib and then face_recognition

**Comment by G90DD** [comment]
Linux MInt 18.3

I will set up a vm and let you know,

thanks
