### ISSUE TITLE
ModuleNotFoundError: No module named 'grabber.facebook'

### ISSUE THREAD

**Issue by blinhares** [ThoughtfulDev/EagleEye#57]
i got this error... 

root@kali:~/EagleEye# python3 eagle-eye.py 
Traceback (most recent call last):
  File "eagle-eye.py", line 10, in <module>
    from grabber.facebook import FBGrabber, FBProfileGrabber
ModuleNotFoundError: No module named 'grabber.facebook'

**Comment by ThoughtfulDev** [comment]
Have you cloned the entire repo?
Does the file grabber/Facebook.py exist?

**Comment by blinhares** [comment]
Yes for both questions! I have use this comand to get install:

wget https://raw.githubusercontent.com/ThoughtfulDev/EagleEye/master/install.sh && chmod +x install.sh && ./install.sh

And I did manually and returned the same error.

**Comment by ThoughtfulDev** [comment]
Thats weird.
Can you go into a python 3.6 (or higher) interactive shell from the directory of EagleEye and import grabber.facebook manually? e.g from `grabber.facebook import FBGrabber`

**Comment by blinhares** [comment]
Sure! I got the same error :( 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'grabber.facebook'

Inside de grabber folder i try to import facebook.py with: import facebook. I got this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/EagleEye/grabber/facebook.py", line 6, in <module>
    import utils.config as cfg
ModuleNotFoundError: No module named 'utils'

I pip install utils, them import but when i try import facebook from grabber i got the same error

**Comment by ThoughtfulDev** [comment]
Utils.config is included. No need to pip it.
Honestly no idea.
Seems like you run as root? Try running as a normal user in their home folder

**Comment by blinhares** [comment]
I install on ubuntu and the error is gone... but when a execute the progrma i got this:
![image](https://user-images.githubusercontent.com/39996506/54494890-b1c4e300-48bd-11e9-8f02-8610c64b63d7.png)

**Comment by Alefunshow** [comment]
I have the same error

**Comment by ThoughtfulDev** [comment]
Use the latest geckodriver release: https://github.com/mozilla/geckodriver/releases/tag/v0.24.0
I used that + Firefox 66.0
