### ISSUE TITLE
eagleeye in a web application?

### ISSUE THREAD

**Issue by 20chix** [ThoughtfulDev/EagleEye#60]
Hey before I start with a pull request. 

I opened an issue a while back #14 for pushing this project into the cloud. 

Would you accept an extra folder which will contain the web application which will interface eagleeye from the cloud?

I was thinking to use vue.js as a front end, not sure yet for backend. 

Thanks

**Comment by ThoughtfulDev** [comment]
Yes I will. Vuejs sounds good :) I'll be glad to see you progress :)

**Comment by 20chix** [comment]
👍
