### ISSUE TITLE
Eagleeye import fails, even under virtualenv

### ISSUE THREAD

**Issue by Shiva108** [ThoughtfulDev/EagleEye#61]
Ran ./install.sh and pip3 install -r requirements.
Also made virtualenv just for EagleEye to run in.
Tried pip3 install config too.
Still result is as follows:
(eagleeye) ┌─[root@parrot]─[/home/e/EagleEye]
└──╼ #python3 eagle-eye.py 
Traceback (most recent call last):
  File "eagle-eye.py", line 9, in <module>
    import utils.config as cfg
ModuleNotFoundError: No module named 'utils.config'

**Comment by ThoughtfulDev** [comment]
can you run a python3 shell in the eagle i folder and typ import utils.config ? Do you get a error?

**Comment by Shiva108** [comment]
Yes:
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import utils.config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'utils.config'
>>>

**Comment by ThoughtfulDev** [comment]
thats weird.... you are using parrot? Try using a Ubuntu VM please.

**Comment by Shiva108** [comment]
Even if it were to work under ubuntu it doesnt do much for parrot users.

**Comment by ThoughtfulDev** [comment]
thats true. can you go into the utils folder run a python shell and import config ?

I really dont get why it cannot import. seems pythons cwd is wrong?

can you run a python shell in the base dir of eagle eye an type

```
import os
os.getcwd()
```

what does it print?

**Comment by Shiva108** [comment]
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getcwd()
'/home/e/EagleEye/utils'
>>>

**Comment by ThoughtfulDev** [comment]
Please try using docker which has been added in the latest commit: https://github.com/ThoughtfulDev/EagleEye#docker-preferred

**Comment by Shiva108** [comment]
Didnt seem to help:
└──╼ #./entry.sh 
./entry.sh: line 2: cd: /EagleEye: No such file or directory
Traceback (most recent call last):
  File "/home/e/EagleEye/eagle-eye.py", line 14, in <module>
    from grabber.instagram import InstagramGrabber
  File "/home/e/EagleEye/grabber/instagram.py", line 1, in <module>
    from requests_html import HTMLSession
ModuleNotFoundError: No module named 'requests_html'
cp: cannot create regular file '/result/': Not a directory

**Comment by ThoughtfulDev** [comment]
I just tried using docker on Parrot. You did not follow the docker guide you just ran the entry.sh which is wrong.
Please **read** the docker instructions in the README file...
