### ISSUE TITLE
Results Error

### ISSUE THREAD

**Issue by redax2882** [ThoughtfulDev/EagleEye#63]
**Apologies, but I'm going crazy trying to figure out what I've misconfigured.  I keep getting the following error right at the end of a search:**

:: Result
==> Found the following Profiles:

:: Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
  -> Inserting Path
  -> No Prediction given sry...
  -> Collecting Links...(Page 1)
  -> Switching to Page 2
  -> No more pages...

:: Yandex Reverse Image Search
==> Opening Webdriver
==> Uploading Local Images
  -> Inserting Image URL
Traceback (most recent call last):
  File "eagle-eye.py", line 260, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 139, in main
    yandex.collectLinksLocal()
  File "/EagleEye/grabber/yandex.py", line 74, in collectLinksLocal
    elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]
IndexError: list index out of range
cp: cannot stat '/root/EagleEye/*.pdf': No such file or directory

**Here is my entry.sh file:**

#!/bin/bash
cd /EagleEye
python3.6 eagle-eye.py --docker --name "_[person's name]_"

#now copy the result
yes | cp -rf ~/EagleEye/*.pdf ~/EagleEye/result/*.pdf 

**And here is the docker start code that I enter:**

sudo docker run -t --net=host --env="DISPLAY" \
                           --volume="$HOME/.Xauthority:/root/.Xauthority:rw"  \
                           -v  ~/EagleEye/known:/EagleEye/known \
                           -v  ~/EagleEye/result:/result \
                           -v ~/EagleEye/entry.sh:/entry.sh \
                           eagle-eye

**NOTE:  I have the "known" and "result" folders created in the EagleEye directory.**

**What am I doing wrong?**

**Comment by ThoughtfulDev** [comment]
Seems like the Grabber for yandex is broken again.
Please use the - sY flag in entry.sh to skip yandex until i fix It.
