### ISSUE TITLE
aName is not defined when running

### ISSUE THREAD

**Issue by CharlieGai** [ThoughtfulDev/EagleEye#64]
'''
Traceback (most recent call last):
  File "eagle-eye.py", line 260, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
NameError: name 'aName' is not defined
'''

**Comment by ThoughtfulDev** [comment]
Fixed in lasted commit :)
Thanks
