### ISSUE TITLE
Eagle Eye yandax error "IndexError: list index out of range"??

### ISSUE THREAD

**Issue by phonemyatnaing928** [ThoughtfulDev/EagleEye#69]
Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 139, in main
    yandex.collectLinksLocal()
  File "/root/Desktop/TOOLS/Socialvector/EagleEye/grabber/yandex.py", line 74, in collectLinksLocal
    elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]
IndexError: list index out of range

I have this error on eagle eye how do i fix this??

**Comment by ThoughtfulDev** [comment]
Look at issue #58

**Comment by phonemyatnaing928** [comment]
thank
