### ISSUE TITLE
webdriver path error

### ISSUE THREAD

**Issue by hackdrug** [ThoughtfulDev/EagleEye#7]
i a using linux subsystem windows 10 and trying to install eagle eye. As soon i launch .py, there comes up the error. If anyone can help, 

==> Enter the persons name to find on FB: xxxx
==> How many jitters, higher is better [max 100]: 90
==> Opening Webdriver
C:/Users/xxxx/Documents/linux/EagleEye/geckodriver/geckodriver.exe does not exist - install a webdriver

although the geckodriver.exe is in the path place. pleassse help

**Comment by ThoughtfulDev** [comment]
I dont even know if the Linux subsystem for windows supports X Applications such as firefox.
You want that the subsystem uses your Windows FF Installation? I think thats not possible.
And regarding your Error: The Linux subsystem cant access your windows C drive easily (there might be a way i dont know) thats why it says that the webdriver cannot be found. It only sees its Linux Filesystem.

You would probably be better of with using a VM

**Comment by cr4shcod3** [comment]
https://askubuntu.com/questions/870530/how-to-install-geckodriver-in-ubuntu
