### ISSUE TITLE
Error docker use

### ISSUE THREAD

**Issue by BedoM** [ThoughtfulDev/EagleEye#70]
Hello i have this error, on Linux jgdouzi 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux.

My command :

docker run -t --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" -v  /opt/EagleEye/known/:/EagleEye/known -v  /opt/EagleEye/result/:/result -v /opt/EagleEye/entry.sh:/entry.sh eagle-eye

`
root@jgdouzi:/opt/EagleEye# docker run -t --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" -v  /opt/EagleEye/known/:/EagleEye/known -v  /opt/EagleEye/result/:/result -v /opt/EagleEye/entry.sh:/entry.sh eagle-eye
/usr/local/lib/python3.6/dist-packages/weasyprint/document.py:34: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '

███████╗ █████╗  ██████╗ ██╗     ███████╗       ███████╗██╗   ██╗███████╗
██╔════╝██╔══██╗██╔════╝ ██║     ██╔════╝       ██╔════╝╚██╗ ██╔╝██╔════╝
█████╗  ███████║██║  ███╗██║     █████╗ Version █████╗   ╚████╔╝ █████╗  
██╔══╝  ██╔══██║██║   ██║██║     ██╔══╝   0.2   ██╔══╝    ╚██╔╝  ██╔══╝  
███████╗██║  ██║╚██████╔╝███████╗███████╗       ███████╗   ██║   ███████╗
╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝       ╚══════╝   ╚═╝   ╚══════╝
                root, you have been activated                                                                   
    

:: Running in DOCKER MODE
==> Skipping jitters since specified in config.json
==> Opening Webdriver
  -> Collecting Image URLs...(Page 1)

:: Starting Face Recognition
==> Loading known faces
  -> Loading m1.jpeg
  -> Loading m2.jpeg

:: Analyzing
==> Storing Image in /tmp/VQ3ZU0.jpg
==> Analyzing https://scontent-mrs2-1.xx.fbcdn.net/v/t1.0-1/c20.6.74.74a/p86x86/224950_325862937496095_6...
==> Analyzing https://scontent-mrs2-1.xx.fbcdn.net/v/t1.0-1/c0.0.74.74a/p74x74/1014450_1374734769431094_...
==> Analyzing https://scontent-mrs2-1.xx.fbcdn.net/v/t1.0-1/c44.6.74.74a/p86x86/405995_10150994939362264...
==> Removing /tmp/VQ3ZU0.jpg

:: Result
==> Found the following Profiles:

:: Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
  -> Inserting Path
  -> No Prediction given sry...
  -> Collecting Links...(Page 1)
  -> Switching to Page 2
  -> No more pages...
  -> Inserting Path
  -> No Prediction given sry...
  -> Collecting Links...(Page 1)
  -> Switching to Page 2
  -> No more pages...

:: Yandex Reverse Image Search
==> Opening Webdriver
==> Uploading Local Images
  -> Inserting Image URL
Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 139, in main
    yandex.collectLinksLocal()
  File "/EagleEye/grabber/yandex.py", line 74, in collectLinksLocal
    elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 410, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

`

**Comment by phonemyatnaing928** [comment]
open issue #58

**Comment by BedoM** [comment]
I use this : docker run -t --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" -v /opt/EagleEye/known/:/EagleEye/known -v /opt/EagleEye/result/:/result -v /opt/EagleEye/entry.sh:/entry.sh eagle-eye

How fix ?

**Comment by ThoughtfulDev** [comment]
Hey @BedoM look at issue #58
You can change the startup parameter of the docker container in the file `entry.sh`.
Just add `--skipyandex`.
I will make this the default option since yandex is broken right now.
