### ISSUE TITLE
Eagle-eye crashed ( version installed ont the computer)

### ISSUE THREAD

**Issue by dummys** [ThoughtfulDev/EagleEye#78]
As the docker version is not working, I'm trying to use the normal version and I get a crash again...  

-> Inserting Image URL
Traceback (most recent call last):
  File "eagle-eye.py", line 261, in <module>
    main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 139, in main
    yandex.collectLinksLocal()
  File "/home/man/works/tools/recon/EagleEye/grabber/yandex.py", line 74, in collectLinksLocal
    elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]
IndexError: list index out of range

**Comment by ThoughtfulDev** [comment]
Yandex is broken. Please disable it with `--skipyandex`
