### ISSUE TITLE
Face Recognition issues

### ISSUE THREAD

**Issue by Th3F0x-code** [ThoughtfulDev/EagleEye#79]
Face Recognition does not work

`Traceback (most recent call last):`
 ` File "eagle-eye.py", line 261, in <module>`
   `main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile,` `dockerMode=aDocker, dockerName=aName)`
 `File "eagle-eye.py", line 139, in main`
    `yandex.collectLinksLocal()`
  `File "/home/thefox/Scrivania/tools/Information/EagleEye/grabber/yandex.py", line 74, in` `collectLinksLocal`
  `  elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div`                                                                                      `/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]`
`IndexError: list index out of range`

**Comment by ThoughtfulDev** [comment]
Yandex is broken. Please disable it with `--skipyandex`
