### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Th3F0x-code** [ThoughtfulDev/EagleEye#80]
it still does not work even after using the --skipyandex option

**==> Analyzing https://scontent-mxp1-1.xx.fbcdn.net/v/t1.0-1/c22.0.74.74a/p74x74/1379841_1015000455280190...**
`Traceback (most recent call last):`
  `File "eagle-eye.py", line 261, in <module>`
    `main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile,`
`dockerMode=aDocker, dockerName=aName)`
  `File "eagle-eye.py", line 104, in main`
    `profile_links, profile_imgs = r.getValidLinksAndImg(name)`
  `File "/home/thefox/Desktop/tools/Information/EagleEye/face_recog.py", line 86, in`
`getValidLinksAndImg`
    `valid_indexes = self.constructIndexes(label)`
 `File "/home/thefox/Desktop/tools/Information/EagleEye/face_recog.py", line 54, in` `constructIndexes`
    `urlretrieve(i, tmp_path)`
  `File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve`
   `with contextlib.closing(urlopen(url, data)) as fp:`
 `File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen`
   `return opener.open(url, data, timeout)`
 `File "/usr/lib/python3.7/urllib/request.py", line 531, in open`
    `response = meth(req, response)`
`File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response`
  `'http', request, response, code, msg, hdrs)`
 `File "/usr/lib/python3.7/urllib/request.py", line 569, in error`
 `return self._call_chain(*args)`
`File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain`
   `result = func(*args)`
`File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default`
`raise HTTPError(req.full_url, code, msg, hdrs, fp)`
`urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by ThoughtfulDev** [comment]
Does that happen with every image and/or name?

**Comment by Th3F0x-code** [comment]
Yes, it happens with every image and every name with which I tried

**Comment by ThoughtfulDev** [comment]
Can you provide the name and image?

**Comment by Th3F0x-code** [comment]
I'm sorry but I can not

**Comment by ThoughtfulDev** [comment]
404 not found meaning it cannot find the image on fb.

Okay you can do the following.
go in line 53 or face_recog.py:
https://github.com/ThoughtfulDev/EagleEye/blob/master/face_recog.py#L53
And change it to:
`console.task('Analyzing {0}...'.format(i.strip()))`
It should then print the full image link which you can copy and see for yourself if the FB profile image link return a 404.

**Comment by Th3F0x-code** [comment]
Yes, it worked, thank you: D
