### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.console'

### ISSUE THREAD

**Issue by LynxCat777** [ThoughtfulDev/EagleEye#81]
This is the following error that I recieve - 
Traceback (most recent call last):
  File "eagle-eye.py", line 8, in <module>
    import utils.console as console
ModuleNotFoundError: No module named 'utils.console'
i looked at the file and it seems like console and config isn't in classes.

**Comment by ThoughtfulDev** [comment]
Use python 3.6 or higher.

**Comment by arcillus** [comment]
raceback (most recent call last):
  File "eagle-eye.py", line 12, in <module>
    from grabber.instagram import InstagramGrabber
  File "/root/EagleEye/grabber/instagram.py", line 1, in <module>
    from requests_html import HTMLSession
ModuleNotFoundError: No module named 'requests_html'

What should I do?
