### ISSUE TITLE
Error in Yandex Reverse Image Search

### ISSUE THREAD

**Issue by cucodev** [ThoughtfulDev/EagleEye#82]
### :: Yandex Reverse Image Search

> ==> Opening Webdriver
> ==> Uploading Local Images
>   -> Inserting Image URL
> 
> Traceback (most recent call last):
> File "eagle-eye.py", line 261, in <module>
>     main(skipFB=args.skipfb, skipY=args.skipyandex, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
>   File "eagle-eye.py", line 139, in main
>     yandex.collectLinksLocal()
>   File "/home/sofyan/app/EagleEye/grabber/yandex.py", line 74, in collectLinksLocal
>     elems = driver.find_elements_by_xpath('/html/body/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/div/div[1]/div[2]/form/div[1]/span/span[2]')[0]

**Comment by ThoughtfulDev** [comment]
Yandex is broken. Please disable it with --skipyandex
