### ISSUE TITLE
I can't to finalize the scan

### ISSUE THREAD

**Issue by swag-gh0st** [ThoughtfulDev/EagleEye#88]
When I was scanning, it showed this error
https://github.com/ThoughtfulDev/EagleEye/issues
:: Result
==> Found the following Profiles:

:: Google Reverse Image Search
==> Opening Webdriver

:: Uploading Local Known Images
Traceback (most recent call last):
  File "eagle-eye.py", line 228, in <module>
    main(skipFB=args.skipfb, FBUrls=[], jsonRep=jsonRepFile, dockerMode=aDocker, dockerName=aName)
  File "eagle-eye.py", line 130, in main
    g.collectLinksLocal()
  File "/home/kali/Documents/Tools/EagleEye/grabber/google.py", line 134, in collectLinksLocal
    elems = driver.find_elements_by_xpath(self.PHOTO_XPATH)[0]
IndexError: list index out of range

Can you help me?

**Comment by abbascs** [comment]
I have also this problem.
Any help?
