### ISSUE TITLE
ModuleNotFoundError: No module named 'termcolor'

### ISSUE THREAD

**Issue by hackdrug** [ThoughtfulDev/EagleEye#9]
i am sure that i install all the pre-request and no error in that.

as soon in launch python3 eagle-eye.py here comes the error

Traceback (most recent call last):
  File "eagle-eye.py", line 8, in <module>
    import utils.console as console
  File "/root/EagleEye/utils/console.py", line 1, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

help me please. i know i am noob

**Comment by ThoughtfulDev** [comment]
First make sure that you are using `python3`
Then just to make sure everything is installed do
```
$ sudo pip3 install -r requirements.txt
$ sudo pip3 install --upgrade beautifulsoup4 html5lib spry
```

Go into the interactive python shell `python3`
the output when importing termcolor should be:
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import termcolor
>>>
```

**Comment by hackdrug** [comment]
hi thank you for your reply. 
when i did 

$ sudo pip3 install -r requirements.txt -> requirement already satisfied
$ sudo pip3 install --upgrade beautifulsoup4 html5lib spry -> requirement already up-to-date

and for this 

Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import termcolor
>>>

it said

Python 3.6.3 (default, Apr  6 2018) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import termcolor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'termcolor'

what did i do wrong?

**Comment by ThoughtfulDev** [comment]
Maybe you have a pip for python 3.5 and for 3.6 list all your pip binaries with
```
$ ls /usr/bin | grep pip
```

For example my arch install has a pip3 (for python 3.5) and a pip3.6 (for python 3.6)

**Comment by hackdrug** [comment]
ls /usr/bin | grep pip
lesspipe
pip
pip2
pip3
pipal

pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

>>> import site; site.getsitepackages()             
['/usr/local/lib/python3.6/site-packages']

what to do now

**Comment by hackdrug** [comment]
locate termcolor
/usr/lib/python2.7/dist-packages/termcolor-1.1.0.egg-info
/usr/lib/python2.7/dist-packages/termcolor.py
/usr/lib/python3/dist-packages/termcolor-1.1.0.egg-info
/usr/lib/python3/dist-packages/termcolor.py
/usr/lib/python3/dist-packages/__pycache__/termcolor.cpython-36.pyc
/usr/share/doc/python-termcolor
/usr/share/doc/python3-termcolor
/usr/share/doc/python-termcolor/CHANGES.rst
/usr/share/doc/python-termcolor/README.rst
/usr/share/doc/python-termcolor/changelog.Debian.gz
/usr/share/doc/python-termcolor/copyright
/usr/share/doc/python3-termcolor/CHANGES.rst
/usr/share/doc/python3-termcolor/README.rst
/usr/share/doc/python3-termcolor/changelog.Debian.gz
/usr/share/doc/python3-termcolor/copyright
/usr/share/pyshared/termcolor-1.1.0.egg-info
/usr/share/pyshared/termcolor.py
/usr/share/sqlmap/thirdparty/termcolor
/usr/share/sqlmap/thirdparty/termcolor/__init__.py
/usr/share/sqlmap/thirdparty/termcolor/__init__.pyc
/usr/share/sqlmap/thirdparty/termcolor/termcolor.py
/usr/share/sqlmap/thirdparty/termcolor/termcolor.pyc
/var/cache/apt/archives/python3-termcolor_1.1.0-1_all.deb
/var/lib/dpkg/info/python-termcolor.list
/var/lib/dpkg/info/python-termcolor.md5sums
/var/lib/dpkg/info/python-termcolor.postinst
/var/lib/dpkg/info/python-termcolor.prerm
/var/lib/dpkg/info/python3-termcolor.list
/var/lib/dpkg/info/python3-termcolor.md5sums
/var/lib/dpkg/info/python3-termcolor.postinst
/var/lib/dpkg/info/python3-termcolor.prerm

i am using kali linux on vmware

**Comment by ThoughtfulDev** [comment]
Try using the normal `pip` not `pip3` to install the dependencies. I just used the pre.sh script on a Kali Linux Live Boot and it worked fine.

**Comment by hackdrug** [comment]
i did that.. still no module name termcolor. if i may know, what OS did u use to run the program? cause i really want to use this program

**Comment by ThoughtfulDev** [comment]
My personal Machine is Ubuntu 16.04.
I also tried it on a Kali Linux Live Boot (2018.1) and on a XUbuntu 16.04 Live Boot.
It worked perfectly on all of those Machines.

**Note: If you are using Firefox ESR(like Kali does) please use the Geckodriver Version 17**
