### ISSUE TITLE
Adding some results can be helpful for adoption

### ISSUE THREAD

**Issue by NightMachinary** [ThoughtfulDev/EagleEye#95]
Preferably, you run this for 3 of your friends in random and post the results in the readme. This helps, because I often find popular AI-using Github projects don't really deliver results and are more "technical achievements", so seeing some "demos" definitely helps engender the trust needed to build/install the project.

**Comment by ThoughtfulDev** [comment]
Thanks for the suggestion. But i am sure you understand that i will not run this for my friends and publish the results here publically. There is a result example of an actor in the repository (Example.pdf).
