### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ViperNetwork** [ThoughtfulDev/EagleEye#96]
What should I enter in "config.json" file for the web-driver I don't understand it... I have tried the driver for my chrome but it does not load. I did with firefox's driver but it still gives the error that there should be a webdriver entered in the path.
Please help IN DETAILS

**Comment by ThoughtfulDev** [comment]
Download the webdriver for firefox and then insert the webdrive path. Make sure to use the correct path.

**Comment by ViperNetwork** [comment]
I am just script kiddy, if the web deiver is not installed then How can I
use the firefox browser...please explain

**Comment by ThoughtfulDev** [comment]
install firefox.
download the webdriver here: https://github.com/mozilla/geckodriver/releases
put it in a accessible path
enter that path in config.json.
